
services:

    participant0:
        image: fedstellar
        restart: no
        volumes:
            - D:\MasterProject\fedstellar-venv\Scripts\fedstellar:/fedstellar
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ipc: host
        privileged: true
        command:
            - /bin/bash
            - -c
            - |
                ifconfig && echo '192.168.50.1 host.docker.internal' >> /etc/hosts && python3.8 /fedstellar/fedstellar/node_start.py /fedstellar/app/config/fedstellar_DFL_29_11_2023_03_10_37/participant_0.json
        networks:
            fedstellar-net-scenario:
                ipv4_address: 192.168.50.2
            fedstellar-net-base:

    participant1:
        image: fedstellar
        restart: no
        volumes:
            - D:\MasterProject\fedstellar-venv\Scripts\fedstellar:/fedstellar
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ipc: host
        privileged: true
        command:
            - /bin/bash
            - -c
            - |
                ifconfig && echo '192.168.50.1 host.docker.internal' >> /etc/hosts && python3.8 /fedstellar/fedstellar/node_start.py /fedstellar/app/config/fedstellar_DFL_29_11_2023_03_10_37/participant_1.json
        networks:
            fedstellar-net-scenario:
                ipv4_address: 192.168.50.3
            fedstellar-net-base:

    participant2:
        image: fedstellar
        restart: no
        volumes:
            - D:\MasterProject\fedstellar-venv\Scripts\fedstellar:/fedstellar
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ipc: host
        privileged: true
        command:
            - /bin/bash
            - -c
            - |
                ifconfig && echo '192.168.50.1 host.docker.internal' >> /etc/hosts && python3.8 /fedstellar/fedstellar/node_start.py /fedstellar/app/config/fedstellar_DFL_29_11_2023_03_10_37/participant_2.json
        networks:
            fedstellar-net-scenario:
                ipv4_address: 192.168.50.4
            fedstellar-net-base:


networks:
    fedstellar-net-scenario:
        name: fedstellar-net-scenario
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.50.1/24
                  gateway: 192.168.50.1     
    fedstellar-net-base:
        name: fedstellar-net-base
        external: true
